### ISSUE TITLE
Publishing the package

### ISSUE THREAD

**Issue by mweststrate** [antitoxic/mobx-redux-devtools#1]
Hey @antitoxic 

I just remembered that I promised to help you with publishing the package. Sorry for forgetting about that! What can I help you with :) ?

**Comment by antitoxic** [comment]
:) Hey. Glad to hear from you. Well, I've only published a package to npm once and it was a few years ago. I remember it being a very painful process especially updates and version management. So I think I was doing it wrong. 

I would be grateful for any help on that. I'm happy to share ownership of the project. I'm not a crazed credit keeper :) 

Basically, open to anything to see this package help people with development.

**Comment by antitoxic** [comment]
@mweststrate ?

I got something published: https://www.npmjs.com/package/mobx-redux-devtools

Can you check whether it's missing something and that it's done the right way?

**Comment by mweststrate** [comment]
Sorry, didn't find a time to look through the code earlier :( But looks decent. Nice leveraging of reaction and encouragment of createTransformer, that should scale well.

**Comment by mweststrate** [comment]
Be sure to take a look at https://github.com/zalmoxisus/mobx-remotedev though. Seems quite similar but is based on the spy api. That avoids the need for a custom serializer.

**Comment by antitoxic** [comment]
Oh, well. @zalmoxisus 's version is much better. I think I'll give up on this. Thank's for the heads up.

**Comment by mweststrate** [comment]
well proves it was a good idea 😉. thanks for the effort and apologies for
not really helping you out

Op vr 22 jul. 2016 10:27 schreef Anton Stoychev notifications@github.com:
