### ISSUE TITLE
Refer to mobx-remotedev in readme

### ISSUE THREAD

**Issue by jefffriesen** [antitoxic/mobx-redux-devtools#2]
Sounds like you're giving up on this repo: https://github.com/antitoxic/mobx-redux-devtools/issues/1

If so, maybe mention that at the top of the readme and mention mobx-remotedev? It would be cool to mention the different approaches and why mobx-remotedev is a better approach if you think so?

**Comment by antitoxic** [comment]
Done. Thanks for pinging me. 👍

**Comment by jefffriesen** [comment]
Nice writeup!
